<?php namespace App\Controllers;
/**
* THIS CONTROLER CODEIGNITER 4
* Codeigniter Version 4.x
* Generated by LigatCode
**/
use App\Models\IkkModel;

class Ikk extends BaseController
{
    /**
	 * Class constructor.
     */	
    protected $PageData;
    protected $Model; //Default Models Of this Controler
    protected $pager;
	public function __construct()
	{
		$this->Model = new IkkModel(); //Set Default Models Of this Controler
        $this->PageData = $this->attributePage(); //Attribute Of Page
        $pager = \Config\Services::pager();
    }
    
    //ATRIBUTE THIS PAGE
    private function attributePage()
	{
		return  [
			'title' => 'LigatCode | Ikk',
			'app' => 'LigatCode',
		];
    }

    //INDEX 
    public function index()
	{
        $request = service('request');
		$searchData = $request->getGet(); // OR $this->request->getGet();

		$search = "";
		if (isset($searchData) && isset($searchData['search'])) {
			$search = $searchData['search'];
		}

        if ($search == '') {
			$paginateData = $this->Model->paginate(5);
		} else {
			$paginateData = $this->Model->select('*')
					    ->orLike('id', $search)
					    ->orLike('ikk', $search)
					    ->orLike('satuan', $search)
					    ->orLike('capaian', $search)
					    ->orLike('sumber_data', $search)
					    ->orLike('id_sub_urusan', $search)
					    ->paginate(5);
        }$data = [
			'AttributePage' =>$this->PageData,
			'content' => 'List Pages',
            'data' => $paginateData,
            'pager' => $this->Model->pager,
            'number' => nomorTabel($this->request->getVar('page'), 5),
            'search'=>$search
		];
		return view('ikk/index_ikk', $data);
    }

    //READ
    public function read($id)
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Read Pages',
			'data' => $this->Model->find($id) //find on data
		];
		return view('ikk/read_ikk', $data);
    }

    //CREATE
    public function create()
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Create Pages',
			'action' => site_url('Ikk/create_action'),
			'data' =>   [
					     'id' => set_value('id'),
					     'ikk' => set_value('ikk'),
					     'satuan' => set_value('satuan'),
					     'capaian' => set_value('capaian'),
					     'sumber_data' => set_value('sumber_data'),
					     'id_sub_urusan' => set_value('id_sub_urusan'),
					    ]
		];
		return view('ikk/form_ikk', $data);
    }
    
    //ACTION CREATE
	public function create_action()
	{
		$data =[
				     'id' => $this->request->getVar('id'),
				     'ikk' => $this->request->getVar('ikk'),
				     'satuan' => $this->request->getVar('satuan'),
				     'capaian' => $this->request->getVar('capaian'),
				     'sumber_data' => $this->request->getVar('sumber_data'),
				     'id_sub_urusan' => $this->request->getVar('id_sub_urusan'),
        
				];
		$this->Model->save($data);
		session()->setFlashdata('message', 'Create Record Success');
		return redirect()->to(base_url('/Ikk'));
    }
    
    //UPDATE
	public function update($id)
	{
		$dataFind = $this->Model->find($id);
		if($dataFind == false){
			return redirect()->to(base_url('/Ikk'));
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Edite Pages',
			'action' => 'ikk/update_action',
			'data' => $this->Model->find($id),
        ];
		session()->setFlashdata('message', 'Update Record Success');
		return view('ikk/form_ikk', $data);
    }
    
    //ACTION UPDATE
   	public function update_action()
	{
		$id = $this->request->getVar('id');
		$row = $this->Model->find(['id' => $id]);

			$data =[
				    'id' => $this->request->getVar('id'),
				    'ikk' => $this->request->getVar('ikk'),
				    'satuan' => $this->request->getVar('satuan'),
				    'capaian' => $this->request->getVar('capaian'),
				    'sumber_data' => $this->request->getVar('sumber_data'),
				    'id_sub_urusan' => $this->request->getVar('id_sub_urusan'),
                    ];
            $this->Model->save($data);
			session()->setFlashdata('message', 'Update Record Success');
			
			return redirect()->to(base_url('ikk'));
		
	}

    //DELETE
	public function delete($id)
	{
		$row = $this->Model->find(['id' => $id]);
		if ($row) {
            $this->Model->delete($id);
            session()->setFlashdata('message', 'Delete Record Success');
            return redirect()->to(base_url('/ikk'));
        } else {
            session()->setFlashdata('message', 'Record Not Found');
            return redirect()->to(base_url('/ikk'));
        }

    }

    //RULES
    public function _rules() 
    {
	$this->form_validation->set_rules('ikk', 'ikk', 'trim|required');
	$this->form_validation->set_rules('satuan', 'satuan', 'trim|required');
	$this->form_validation->set_rules('capaian', 'capaian', 'trim|required');
	$this->form_validation->set_rules('sumber_data', 'sumber data', 'trim|required');
	$this->form_validation->set_rules('id_sub_urusan', 'id sub urusan', 'trim|required|numeric');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Ikk.php */
 /* Location: ./app/controllers/Ikk.php */
 /* Please DO NOT modify this information : */
 /* Generated by Ligatcode Codeigniter 4 CRUD Generator 2022-02-19 03:33:21 */