<?php

namespace App\Controllers;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use App\Models\UrusanModel;

class Laporan extends BaseController
{
	/**
	 * Class constructor.
	 */
	protected $PageData;
	protected $UrusanModel; //Default Models Of this Controler
	public function __construct()
	{
		$this->MUrusan = new UrusanModel(); //Set Default Models Of this Controler
		$this->PageData = $this->attributePage(); //Attribute Of Page
	}

	//ATRIBUTE THIS PAGE
	private function attributePage()
	{
		return  [
			'title' => 'LigatCode | Ikk',
			'app' => 'LigatCode',
		];
	}

	public function outputKeluaran()
	{
		$request = service('request');
		$db = \Config\Database::connect();
		$getUrusan = $db->query("select *,ee.name as sumber_data from urusan as aa
		inner join sub_urusan as bb on aa.id=bb.id_urusan
		inner join ikk as cc on bb.id=cc.id_sub_urusan
		inner join rumus as dd on cc.id=dd.id_ikk
		inner join sy_category as ee on dd.sumber_data=ee.id
		where aa.output_outcome='OP'
		order by aa.id asc, bb.id asc, cc.id asc, dd.id")->getResult();
		$arr = [];
		foreach ($getUrusan as $k => $v) {
			$arr[$v->urusan][$v->sub_urusan][$v->ikk][$v->rumus] = $v;
		}
		// wfDebug($data);
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'List Pages',
			'data' => $arr,
		];
		return view('laporan/output_keluaran', $data);
	}

	public function outcomeHasil()
	{
		$request = service('request');
		$db = \Config\Database::connect();
		$getUrusan = $db->query("select *,ee.name as sumber_data from urusan as aa
		inner join sub_urusan as bb on aa.id=bb.id_urusan
		inner join ikk as cc on bb.id=cc.id_sub_urusan
		inner join rumus as dd on cc.id=dd.id_ikk
		inner join sy_category as ee on dd.sumber_data=ee.id
		where aa.output_outcome='OC'
		order by aa.id asc, bb.id asc, cc.id asc, dd.id")->getResult();
		$arr = [];
		foreach ($getUrusan as $k => $v) {
			$arr[$v->urusan][$v->sub_urusan][$v->ikk][$v->rumus] = $v;
		}
		// wfDebug($data);
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'List Pages',
			'data' => $arr,
		];
		return view('laporan/outcome_hasil', $data);
	}

	public function penunjang()
	{
		$request = service('request');
		$db = \Config\Database::connect();
		$getUrusan = $db->query("select *,ee.name as sumber_data from urusan as aa
		inner join sub_urusan as bb on aa.id=bb.id_urusan
		inner join ikk as cc on bb.id=cc.id_sub_urusan
		inner join rumus as dd on cc.id=dd.id_ikk
		inner join sy_category as ee on dd.sumber_data=ee.id
		where aa.output_outcome='PN'
		order by aa.id asc, bb.id asc, cc.id asc, dd.id")->getResult();
		$arr = [];
		foreach ($getUrusan as $k => $v) {
			$arr[$v->urusan][$v->sub_urusan][$v->ikk][$v->rumus] = $v;
		}
		// wfDebug($data);
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'List Pages',
			'data' => $arr,
		];
		return view('laporan/penunjang', $data);
	}

	public function srcMakroBappeda()
	{
		$data = [];
		return view('laporan/makro/src_makro', $data);
	}

	public function prinMakroBappeda()
	{
		db_connect()->query("SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));");
		$data = [
			'data' => db_connect()->query("select * from makro group by id,ikk order by id asc")->getResult(),
			'tahun' => $_POST['tahun']
		];
		return view('laporan/makro/prin_makro', $data);
	}
}

/* End of file Ikk.php */
 /* Location: ./app/controllers/Ikk.php */
 /* Please DO NOT modify this information : */
 /* Generated by Ligatcode Codeigniter 4 CRUD Generator 2022-02-19 03:33:21 */