<?php

namespace App\Controllers;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use App\Models\MakroModel;

class Makro extends BaseController
{
	/**
	 * Class constructor.
	 */
	protected $PageData;
	protected $Model; //Default Models Of this Controler
	protected $pager;
	public function __construct()
	{
		$this->Model = new MakroModel(); //Set Default Models Of this Controler
		$this->PageData = $this->attributePage(); //Attribute Of Page
		$pager = \Config\Services::pager();
	}

	//ATRIBUTE THIS PAGE
	private function attributePage()
	{
		return  [
			'title' => 'WinkCode | Makro',
			'app' => 'WinkCode',
		];
	}

	//INDEX 
	public function index()
	{
		$request = service('request');
		$searchData = $request->getGet(); // OR $this->request->getGet();

		$search = "";
		if (isset($searchData) && isset($searchData['search'])) {
			$search = $searchData['search'];
		}

		if ($search == '') {
			$paginateData = $this->Model->paginate(5);
		} else {
			$paginateData = $this->Model->select('*')
				->orLike('id', $search)
				->orLike('ikk', $search)
				->orLike('tahun', $search)
				->orLike('capaian_kinerja', $search)
				->orLike('laju_kinerja', $search)
				->paginate(5);
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'List Pages',
			'data' => $paginateData,
			'pager' => $this->Model->pager,
			'number' => nomorTabel($this->request->getVar('page'), 5),
			'search' => $search
		];
		return view('makro/index_makro', $data);
	}

	//READ
	public function read($id)
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Read Pages',
			'data' => $this->Model->find($id) //find on data
		];
		return view('makro/read_makro', $data);
	}

	//CREATE
	public function create()
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Create Pages',
			'action' => site_url('Makro/create_action'),
			'data' =>   [
				'id' => set_value('id'),
				'ikk' => set_value('ikk'),
				'tahun' => set_value('tahun'),
				'capaian_kinerja' => set_value('capaian_kinerja'),
				'laju_kinerja' => set_value('laju_kinerja'),
			]
		];
		return view('makro/form_makro', $data);
	}

	//ACTION CREATE
	public function create_action()
	{
		$data = [
			'id' => $this->request->getVar('id'),
			'ikk' => $this->request->getVar('ikk'),
			'tahun' => $this->request->getVar('tahun'),
			'capaian_kinerja' => $this->request->getVar('capaian_kinerja'),
			'laju_kinerja' => $this->request->getVar('laju_kinerja'),

		];
		$this->Model->save($data);
		session()->setFlashdata('message', 'Create Record Success');
		return redirect()->to(base_url('/Makro'));
	}

	//UPDATE
	public function update($id)
	{
		$dataFind = $this->Model->find($id);
		if ($dataFind == false) {
			return redirect()->to(base_url('/Makro'));
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Edite Pages',
			'action' => 'makro/update_action',
			'data' => $this->Model->find($id),
		];
		session()->setFlashdata('message', 'Update Record Success');
		return view('makro/form_makro', $data);
	}

	//ACTION UPDATE
	public function update_action()
	{
		$id = $this->request->getVar('id');
		$row = $this->Model->find(['id' => $id]);

		$data = [
			'id' => $this->request->getVar('id'),
			'ikk' => $this->request->getVar('ikk'),
			'tahun' => $this->request->getVar('tahun'),
			'capaian_kinerja' => $this->request->getVar('capaian_kinerja'),
			'laju_kinerja' => $this->request->getVar('laju_kinerja'),
		];
		$this->Model->save($data);
		session()->setFlashdata('message', 'Update Record Success');

		return redirect()->to(base_url('makro'));
	}

	//DELETE
	public function delete($id)
	{
		$row = $this->Model->find(['id' => $id]);
		if ($row) {
			$this->Model->delete($id);
			session()->setFlashdata('message', 'Delete Record Success');
			return redirect()->to(base_url('/makro'));
		} else {
			session()->setFlashdata('message', 'Record Not Found');
			return redirect()->to(base_url('/makro'));
		}
	}

	//RULES
	public function _rules()
	{
		$this->form_validation->set_rules('ikk', 'ikk', 'trim|required');
		$this->form_validation->set_rules('tahun', 'tahun', 'trim|required');
		$this->form_validation->set_rules('capaian_kinerja', 'capaian kinerja', 'trim|required');
		$this->form_validation->set_rules('laju_kinerja', 'laju kinerja', 'trim|required');

		$this->form_validation->set_rules('id', 'id', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
	}
}

/* End of file Makro.php */
 /* Location: ./app/controllers/Makro.php */
 /* Please DO NOT modify this information : */
 /* Generated by Ligatcode Codeigniter 4 CRUD Generator 2022-04-12 03:28:01 */