<?php

namespace App\Controllers;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use App\Models\RumusModel;

class Rumus extends BaseController
{
	/**
	 * Class constructor.
	 */
	protected $PageData;
	protected $Model; //Default Models Of this Controler
	protected $pager;
	public function __construct()
	{
		$this->Model = new RumusModel(); //Set Default Models Of this Controler
		$this->PageData = $this->attributePage(); //Attribute Of Page
		$pager = \Config\Services::pager();
	}

	//ATRIBUTE THIS PAGE
	private function attributePage()
	{
		return  [
			'title' => 'LigatCode | Rumus',
			'app' => 'LigatCode',
		];
	}

	//INDEX 
	public function index()
	{
		$request = service('request');
		$searchData = $request->getGet(); // OR $this->request->getGet();

		$search = "";
		if (isset($searchData) && isset($searchData['search'])) {
			$search = $searchData['search'];
		}

		if ($search == '') {
			$paginateData = $this->Model->paginate(5);
		} else {
			$paginateData = $this->Model->select('*')
				->orLike('id', $search)
				->orLike('rumus', $search)
				->orLike('elemen_data', $search)
				->orLike('id_ikk', $search)
				->paginate(5);
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'List Pages',
			'data' => $paginateData,
			'pager' => $this->Model->pager,
			'number' => nomorTabel($this->request->getVar('page'), 5),
			'search' => $search
		];
		return view('rumus/index_rumus', $data);
	}

	//READ
	public function read($id)
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Read Pages',
			'data' => $this->Model->find($id) //find on data
		];
		return view('rumus/read_rumus', $data);
	}

	//CREATE
	public function create()
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Create Pages',
			'action' => site_url('Rumus/create_action'),
			'data' =>   [
				'id' => set_value('id'),
				'rumus' => set_value('rumus'),
				'elemen_data' => set_value('elemen_data'),
				'id_ikk' => set_value('id_ikk'),
				'sumber_data' => set_value('sumber_data'),
				'file_data_dukung' => set_value('file_data_dukung'),
			]
		];
		return view('rumus/form_rumus', $data);
	}

	//ACTION CREATE
	public function create_action()
	{
		$fileDataDukung = $this->request->getFile('file_data_dukung');
		$isvalid = $this->validate([
			'file_data_dukung' => 'uploaded[file_data_dukung]|max_size[file_data_dukung,1024]',
		]);
		if (!$isvalid) {
			session()->setFlashdata('message', 'Upload file gagal, Periksa file');
			return redirect()->to(base_url('/Rumus/create'));
		}
		$fileDataDukung->move('uploads');
		$fileDataDukungName = "";
		if ($fileDataDukung->hasMoved()) {
			$fileDataDukungName = $fileDataDukung->getName();
		}
		$data = [
			'id' => $this->request->getVar('id'),
			'rumus' => $this->request->getVar('rumus'),
			'elemen_data' => $this->request->getVar('elemen_data'),
			'id_ikk' => $this->request->getVar('id_ikk'),
			'sumber_data' => $this->request->getVar('id_ikk'),
			'file_data_dukung' => $fileDataDukungName,

		];
		$this->Model->save($data);
		session()->setFlashdata('message', 'Create Record Success');
		return redirect()->to(base_url('/Rumus'));
	}

	//UPDATE
	public function update($id)
	{
		$dataFind = $this->Model->find($id);
		if ($dataFind == false) {
			return redirect()->to(base_url('/Rumus'));
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Edite Pages',
			'action' => 'rumus/update_action',
			'data' => $this->Model->find($id),
		];
		session()->setFlashdata('message', 'Update Record Success');
		return view('rumus/form_rumus', $data);
	}

	//ACTION UPDATE
	public function update_action()
	{
		$id = $this->request->getVar('id');
		$row = $this->Model->find(['id' => $id]);

		// wfDebug(APPPATH  . 'public/uploads/' . $row[0]['file_data_dukung']);
		$fileDataDukung = $this->request->getFile('file_data_dukung');
		$isvalid = $this->validate([
			'file_data_dukung' => 'uploaded[file_data_dukung]|max_size[file_data_dukung,1024]',
		]);
		if (!$isvalid) {
			session()->setFlashdata('message', 'Upload file gagal, Periksa file');
			return redirect()->to(base_url('/Rumus/update/' . $id));
		}
		$fileDataDukung->move('uploads');
		$fileDataDukungName = "";
		if ($fileDataDukung->hasMoved()) {
			if (@file_exists((APPPATH  . 'public/uploads/' . $row[0]['file_data_dukung']))) {
				unlink(APPPATH  . 'public/uploads/' . @$row[0]['file_data_dukung']);
			}
			$fileDataDukungName = $fileDataDukung->getName();
		}

		$data = [
			'id' => $this->request->getVar('id'),
			'rumus' => $this->request->getVar('rumus'),
			'elemen_data' => $this->request->getVar('elemen_data'),
			'id_ikk' => $this->request->getVar('id_ikk'),
			'sumber_data' => $this->request->getVar('sumber_data'),
			'file_data_dukung' => $fileDataDukungName,
		];
		$this->Model->save($data);
		session()->setFlashdata('message', 'Update Record Success');

		return redirect()->to(base_url('rumus'));
	}

	//DELETE
	public function delete($id)
	{
		$row = $this->Model->find(['id' => $id]);
		if ($row) {
			$this->Model->delete($id);
			session()->setFlashdata('message', 'Delete Record Success');
			return redirect()->to(base_url('/rumus'));
		} else {
			session()->setFlashdata('message', 'Record Not Found');
			return redirect()->to(base_url('/rumus'));
		}
	}

	//RULES
	public function _rules()
	{
		$this->form_validation->set_rules('rumus', 'rumus', 'trim|required');
		$this->form_validation->set_rules('elemen_data', 'elemen data', 'trim|required');
		$this->form_validation->set_rules('id_ikk', 'id ikk', 'trim|required|numeric');

		$this->form_validation->set_rules('id', 'id', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
	}
}

/* End of file Rumus.php */
 /* Location: ./app/controllers/Rumus.php */
 /* Please DO NOT modify this information : */
 /* Generated by Ligatcode Codeigniter 4 CRUD Generator 2022-02-19 03:33:51 */