<?php

namespace App\Controllers;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use App\Models\SubUrusanModel;
use App\Models\UrusanModel;

class SubUrusan extends BaseController
{
	/**
	 * Class constructor.
	 */
	protected $PageData;
	protected $Model; //Default Models Of this Controler
	protected $UrusanModel;
	protected $pager;
	public function __construct()
	{
		$this->Model = new SubUrusanModel(); //Set Default Models Of this Controler
		$this->UrusanModel = new UrusanModel(); //Set Default Models Of this Controler
		$this->PageData = $this->attributePage(); //Attribute Of Page
		$pager = \Config\Services::pager();
	}

	//ATRIBUTE THIS PAGE
	private function attributePage()
	{
		return  [
			'title' => 'LigatCode | SubUrusan',
			'app' => 'LigatCode',
		];
	}

	//INDEX 
	public function index()
	{
		$request = service('request');
		$searchData = $request->getGet(); // OR $this->request->getGet();

		$search = "";
		if (isset($searchData) && isset($searchData['search'])) {
			$search = $searchData['search'];
		}

		if ($search == '') {
			$paginateData = $this->Model->paginate(5);
		} else {
			$paginateData = $this->Model->select('*')
				->orLike('id', $search)
				->orLike('sub_urusan', $search)
				->orLike('id_urusan', $search)
				->paginate(5);
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'List Pages',
			'data' => $paginateData,
			'pager' => $this->Model->pager,
			'number' => nomorTabel($this->request->getVar('page'), 5),
			'search' => $search
		];
		return view('suburusan/index_sub_urusan', $data);
	}

	public function getRowUrusan($id)
	{
		return $this->UrusanModel->find($id);
	}

	//READ
	public function read($id)
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Read Pages',
			'data' => $this->Model->find($id) //find on data
		];
		return view('suburusan/read_sub_urusan', $data);
	}

	//CREATE
	public function create()
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Create Pages',
			'action' => site_url('SubUrusan/create_action'),
			'data' =>   [
				'id' => set_value('id'),
				'sub_urusan' => set_value('sub_urusan'),
				'id_urusan' => set_value('id_urusan'),
			]
		];
		return view('suburusan/form_sub_urusan', $data);
	}

	//ACTION CREATE
	public function create_action()
	{
		$data = [
			'id' => $this->request->getVar('id'),
			'sub_urusan' => $this->request->getVar('sub_urusan'),
			'id_urusan' => $this->request->getVar('id_urusan'),

		];
		$this->Model->save($data);
		session()->setFlashdata('message', 'Create Record Success');
		return redirect()->to(base_url('/SubUrusan'));
	}

	//UPDATE
	public function update($id)
	{
		$dataFind = $this->Model->find($id);
		if ($dataFind == false) {
			return redirect()->to(base_url('/SubUrusan'));
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Edite Pages',
			'action' => 'suburusan/update_action',
			'data' => $this->Model->find($id),
		];
		session()->setFlashdata('message', 'Update Record Success');
		return view('suburusan/form_sub_urusan', $data);
	}

	//ACTION UPDATE
	public function update_action()
	{
		$id = $this->request->getVar('id');
		$row = $this->Model->find(['id' => $id]);

		$data = [
			'id' => $this->request->getVar('id'),
			'sub_urusan' => $this->request->getVar('sub_urusan'),
			'id_urusan' => $this->request->getVar('id_urusan'),
		];
		$this->Model->save($data);
		session()->setFlashdata('message', 'Update Record Success');

		return redirect()->to(base_url('suburusan'));
	}

	//DELETE
	public function delete($id)
	{
		$row = $this->Model->find(['id' => $id]);
		if ($row) {
			$this->Model->delete($id);
			session()->setFlashdata('message', 'Delete Record Success');
			return redirect()->to(base_url('/suburusan'));
		} else {
			session()->setFlashdata('message', 'Record Not Found');
			return redirect()->to(base_url('/suburusan'));
		}
	}

	//RULES
	public function _rules()
	{
		$this->form_validation->set_rules('sub_urusan', 'sub urusan', 'trim|required');
		$this->form_validation->set_rules('id_urusan', 'id urusan', 'trim|required|numeric');

		$this->form_validation->set_rules('id', 'id', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
	}
}

/* End of file SubUrusan.php */
 /* Location: ./app/controllers/SubUrusan.php */
 /* Please DO NOT modify this information : */
 /* Generated by Ligatcode Codeigniter 4 CRUD Generator 2022-02-19 03:33:40 */