<?php namespace App\Controllers;
/**
* THIS CONTROLER CODEIGNITER 4
* Codeigniter Version 4.x
* Generated by LigatCode
**/
use App\Models\SyMenuModel;

class SyMenu extends BaseController
{
    /**
	 * Class constructor.
     */	
    protected $PageData;
    protected $Model; //Default Models Of this Controler
    protected $pager;
	public function __construct()
	{
		$this->Model = new SyMenuModel(); //Set Default Models Of this Controler
        $this->PageData = $this->attributePage(); //Attribute Of Page
        $pager = \Config\Services::pager();
    }
    
    //ATRIBUTE THIS PAGE
    private function attributePage()
	{
		return  [
			'title' => 'LigatCode | SyMenu',
			'app' => 'LigatCode',
		];
    }

    //INDEX 
    public function index()
	{
        $request = service('request');
		$searchData = $request->getGet(); // OR $this->request->getGet();

		$search = "";
		if (isset($searchData) && isset($searchData['search'])) {
			$search = $searchData['search'];
		}

        if ($search == '') {
			$paginateData = $this->Model->paginate(5);
		} else {
			$paginateData = $this->Model->select('*')
					    ->orLike('id', $search)
					    ->orLike('label', $search)
					    ->orLike('redirect', $search)
					    ->orLike('url', $search)
					    ->orLike('parent', $search)
					    ->orLike('icon', $search)
					    ->orLike('order_no', $search)
					    ->paginate(5);
        }$data = [
			'AttributePage' =>$this->PageData,
			'content' => 'List Pages',
            'data' => $paginateData,
            'pager' => $this->Model->pager,
            'number' => nomorTabel($this->request->getVar('page'), 5),
            'search'=>$search
		];
		return view('symenu/index_sy_menu', $data);
    }

    //READ
    public function read($id)
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Read Pages',
			'data' => $this->Model->find($id) //find on data
		];
		return view('symenu/read_sy_menu', $data);
    }

    //CREATE
    public function create()
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Create Pages',
			'action' => site_url('SyMenu/create_action'),
			'data' =>   [
					     'id' => set_value('id'),
					     'label' => set_value('label'),
					     'redirect' => set_value('redirect'),
					     'url' => set_value('url'),
					     'parent' => set_value('parent'),
					     'icon' => set_value('icon'),
					     'order_no' => set_value('order_no'),
					    ]
		];
		return view('symenu/form_sy_menu', $data);
    }
    
    //ACTION CREATE
	public function create_action()
	{
		$data =[
				     'id' => $this->request->getVar('id'),
				     'label' => $this->request->getVar('label'),
				     'redirect' => $this->request->getVar('redirect'),
				     'url' => $this->request->getVar('url'),
				     'parent' => $this->request->getVar('parent'),
				     'icon' => $this->request->getVar('icon'),
				     'order_no' => $this->request->getVar('order_no'),
        
				];
		$this->Model->save($data);
		session()->setFlashdata('message', 'Create Record Success');
		return redirect()->to(base_url('/SyMenu'));
    }
    
    //UPDATE
	public function update($id)
	{
		$dataFind = $this->Model->find($id);
		if($dataFind == false){
			return redirect()->to(base_url('/SyMenu'));
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Edite Pages',
			'action' => 'symenu/update_action',
			'data' => $this->Model->find($id),
        ];
		session()->setFlashdata('message', 'Update Record Success');
		return view('symenu/form_sy_menu', $data);
    }
    
    //ACTION UPDATE
   	public function update_action()
	{
		$id = $this->request->getVar('id');
		$row = $this->Model->find(['id' => $id]);

			$data =[
				    'id' => $this->request->getVar('id'),
				    'label' => $this->request->getVar('label'),
				    'redirect' => $this->request->getVar('redirect'),
				    'url' => $this->request->getVar('url'),
				    'parent' => $this->request->getVar('parent'),
				    'icon' => $this->request->getVar('icon'),
				    'order_no' => $this->request->getVar('order_no'),
                    ];
            $this->Model->save($data);
			session()->setFlashdata('message', 'Update Record Success');
			
			return redirect()->to(base_url('symenu'));
		
	}

    //DELETE
	public function delete($id)
	{
		$row = $this->Model->find(['id' => $id]);
		if ($row) {
            $this->Model->delete($id);
            session()->setFlashdata('message', 'Delete Record Success');
            return redirect()->to(base_url('/symenu'));
        } else {
            session()->setFlashdata('message', 'Record Not Found');
            return redirect()->to(base_url('/symenu'));
        }

    }

    //RULES
    public function _rules() 
    {
	$this->form_validation->set_rules('label', 'label', 'trim|required');
	$this->form_validation->set_rules('redirect', 'redirect', 'trim|required|numeric');
	$this->form_validation->set_rules('url', 'url', 'trim|required');
	$this->form_validation->set_rules('parent', 'parent', 'trim|required|numeric');
	$this->form_validation->set_rules('icon', 'icon', 'trim|required');
	$this->form_validation->set_rules('order_no', 'order no', 'trim|required|numeric');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file SyMenu.php */
 /* Location: ./app/controllers/SyMenu.php */
 /* Please DO NOT modify this information : */
 /* Generated by Ligatcode Codeigniter 4 CRUD Generator 2022-02-19 03:28:40 */