<?php

namespace App\Controllers;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use App\Models\SyUserModel;

class SyUser extends BaseController
{
	/**
	 * Class constructor.
	 */
	protected $PageData;
	protected $Model; //Default Models Of this Controler
	protected $pager;
	public function __construct()
	{
		$this->Model = new SyUserModel(); //Set Default Models Of this Controler
		$this->PageData = $this->attributePage(); //Attribute Of Page
		$pager = \Config\Services::pager();
	}

	//ATRIBUTE THIS PAGE
	private function attributePage()
	{
		return  [
			'title' => 'LigatCode | SyUser',
			'app' => 'LigatCode',
		];
	}

	//INDEX 
	public function index()
	{
		$request = service('request');
		$searchData = $request->getGet(); // OR $this->request->getGet();

		$search = "";
		if (isset($searchData) && isset($searchData['search'])) {
			$search = $searchData['search'];
		}

		if ($search == '') {
			$paginateData = $this->Model->paginate(5);
		} else {
			$paginateData = $this->Model->select('*')
				->orLike('id', $search)
				->orLike('fullname', $search)
				->orLike('username', $search)
				->orLike('password', $search)
				->orLike('email', $search)
				->orLike('id_group', $search)
				->orLike('foto', $search)
				->orLike('telp', $search)
				->orLike('ip', $search)
				->orLike('last_login', $search)
				->paginate(5);
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Create Pages',
			'data' => $paginateData,
			'pager' => $this->Model->pager,
			'number' => nomorTabel($this->request->getVar('page'), 5),
			'search' => $search
		];
		return view('syuser/index_sy_user', $data);
	}

	//READ
	public function read($id)
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Read Pages',
			'data' => $this->Model->find($id) //find on data
		];
		return view('syuser/read_sy_user', $data);
	}

	//CREATE
	public function create()
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Create Pages',
			'action' => site_url('SyUser/create_action'),
			'data' =>   [
				'id' => set_value('id'),
				'fullname' => set_value('fullname'),
				'username' => set_value('username'),
				'password' => set_value('password'),
				'email' => set_value('email'),
				'id_group' => set_value('id_group'),
				'foto' => set_value('foto'),
				'telp' => set_value('telp'),
				'ip' => set_value('ip'),
				'last_login' => set_value('last_login'),
			]
		];
		return view('syuser/form_sy_user', $data);
	}

	//ACTION CREATE
	public function create_action()
	{


		$data = [
			'id' => $this->request->getVar('id'),
			'fullname' => $this->request->getVar('fullname'),
			'username' => $this->request->getVar('username'),
			'password' => $this->request->getVar('password'),
			'email' => $this->request->getVar('email'),
			'id_group' => $this->request->getVar('id_group'),
			'foto' => $this->request->getVar('foto'),
			'telp' => $this->request->getVar('telp'),
			'ip' => $this->request->getVar('ip'),
			'last_login' => $this->request->getVar('last_login'),

		];
		$this->Model->save($data);
		session()->setFlashdata('message', 'Create Record Success');
		return redirect()->to(base_url('/SyUser'));
	}

	//UPDATE
	public function update($id)
	{
		$dataFind = $this->Model->find($id);
		if ($dataFind == false) {
			return redirect()->to(base_url('/SyUser'));
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Edite Pages',
			'action' => 'syuser/update_action',
			'data' => $this->Model->find($id),
		];
		session()->setFlashdata('message', 'Update Record Success');
		return view('syuser/form_sy_user', $data);
	}

	//ACTION UPDATE
	public function update_action()
	{
		$id = $this->request->getVar('id');
		$row = $this->Model->find(['id' => $id]);

		if ($this->request->getVar('password') == "") {
			$pass = $row->password;
		} else {
			$pass = $this->request->getVar('password');
		}

		$data = [
			'id' => $this->request->getVar('id'),
			'fullname' => $this->request->getVar('fullname'),
			'username' => $this->request->getVar('username'),
			'password' => $pass,
			'email' => $this->request->getVar('email'),
			'id_group' => $this->request->getVar('id_group'),
			'foto' => $this->request->getVar('foto'),
			'telp' => $this->request->getVar('telp'),
			'ip' => $this->request->getVar('ip'),
			'last_login' => $this->request->getVar('last_login'),
		];
		$this->Model->save($data);
		session()->setFlashdata('message', 'Update Record Success');

		return redirect()->to(base_url('syuser'));
	}

	//DELETE
	public function delete($id)
	{
		$row = $this->Model->find(['id' => $id]);
		if ($row) {
			$this->Model->delete($id);
			session()->setFlashdata('message', 'Delete Record Success');
			return redirect()->to(base_url('/syuser'));
		} else {
			session()->setFlashdata('message', 'Record Not Found');
			return redirect()->to(base_url('/syuser'));
		}
	}

	//RULES
	public function _rules()
	{
		$this->form_validation->set_rules('fullname', 'fullname', 'trim|required');
		$this->form_validation->set_rules('username', 'username', 'trim|required');
		$this->form_validation->set_rules('password', 'password', 'trim|required');
		$this->form_validation->set_rules('email', 'email', 'trim|required');
		$this->form_validation->set_rules('id_group', 'id group', 'trim|required|numeric');
		$this->form_validation->set_rules('foto', 'foto', 'trim|required');
		$this->form_validation->set_rules('telp', 'telp', 'trim|required');
		$this->form_validation->set_rules('ip', 'ip', 'trim|required');
		$this->form_validation->set_rules('last_login', 'last login', 'trim|required');

		$this->form_validation->set_rules('id', 'id', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
	}
}

/* End of file SyUser.php */
 /* Location: ./app/controllers/SyUser.php */
 /* Please DO NOT modify this information : */
 /* Generated by Ligatcode Codeigniter 4 CRUD Generator 2022-02-17 07:44:37 */