<?php

namespace App\Controllers;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use App\Models\UrusanModel;

class Urusan extends BaseController
{
	/**
	 * Class constructor.
	 */
	protected $PageData;
	protected $Model; //Default Models Of this Controler
	protected $pager;
	public function __construct()
	{
		$this->Model = new UrusanModel(); //Set Default Models Of this Controler
		$this->PageData = $this->attributePage(); //Attribute Of Page
		$pager = \Config\Services::pager();
	}

	//ATRIBUTE THIS PAGE
	private function attributePage()
	{
		return  [
			'title' => 'LigatCode | Urusan',
			'app' => 'LigatCode',
		];
	}

	//INDEX 
	public function index()
	{
		$request = service('request');
		$searchData = $request->getGet(); // OR $this->request->getGet();

		$search = "";
		if (isset($searchData) && isset($searchData['search'])) {
			$search = $searchData['search'];
		}

		if ($search == '') {
			$paginateData = $this->Model->paginate(5);
		} else {
			$paginateData = $this->Model->select('*')
				->orLike('id', $search)
				->orLike('urusan', $search)
				->orLike('output_outcome', $search)
				->paginate(5);
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'List Pages',
			'data' => $paginateData,
			'pager' => $this->Model->pager,
			'number' => nomorTabel($this->request->getVar('page'), 5),
			'search' => $search
		];
		return view('urusan/index_urusan', $data);
	}

	//READ
	public function read($id)
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Read Pages',
			'data' => $this->Model->find($id) //find on data
		];
		return view('urusan/read_urusan', $data);
	}

	//CREATE
	public function create()
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Create Pages',
			'action' => site_url('Urusan/create_action'),
			'data' =>   [
				'id' => set_value('id'),
				'urusan' => set_value('urusan'),
				'output_outcome' => set_value('output_outcome'),
				'jenis_urusan' => set_value('jenis_urusan'),
			]
		];
		return view('urusan/form_urusan', $data);
	}

	//ACTION CREATE
	public function create_action()
	{
		$data = [
			'id' => $this->request->getVar('id'),
			'urusan' => $this->request->getVar('urusan'),
			'output_outcome' => $this->request->getVar('output_outcome'),
			'jenis_urusan' => $this->request->getVar('jenis_urusan'),

		];
		$this->Model->save($data);
		session()->setFlashdata('message', 'Create Record Success');
		return redirect()->to(base_url('/Urusan'));
	}

	//UPDATE
	public function update($id)
	{
		$dataFind = $this->Model->find($id);
		if ($dataFind == false) {
			return redirect()->to(base_url('/Urusan'));
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Edite Pages',
			'action' => 'urusan/update_action',
			'data' => $this->Model->find($id),
		];
		session()->setFlashdata('message', 'Update Record Success');
		return view('urusan/form_urusan', $data);
	}

	//ACTION UPDATE
	public function update_action()
	{
		$id = $this->request->getVar('id');
		$row = $this->Model->find(['id' => $id]);

		$data = [
			'id' => $this->request->getVar('id'),
			'urusan' => $this->request->getVar('urusan'),
			'output_outcome' => $this->request->getVar('output_outcome'),
			'jenis_urusan' => $this->request->getVar('jenis_urusan'),
		];
		$this->Model->save($data);
		session()->setFlashdata('message', 'Update Record Success');

		return redirect()->to(base_url('urusan'));
	}

	//DELETE
	public function delete($id)
	{
		$row = $this->Model->find(['id' => $id]);
		if ($row) {
			$this->Model->delete($id);
			session()->setFlashdata('message', 'Delete Record Success');
			return redirect()->to(base_url('/urusan'));
		} else {
			session()->setFlashdata('message', 'Record Not Found');
			return redirect()->to(base_url('/urusan'));
		}
	}

	public function getCombo()
	{
		$data = [];
		$db      = db_connect();
		$builder = $db->table('urusan');
		$query = $builder->like('urusan', @$this->request->getVar('q'))
			->select('id, concat(urusan,output_outcome) as text')
			->limit(10)->get();
		$data = $query->getResult();
		echo json_encode($data);
	}


	//RULES
	public function _rules()
	{
		$this->form_validation->set_rules('urusan', 'urusan', 'trim|required');
		$this->form_validation->set_rules('output_outcome', 'output outcome', 'trim|required');

		$this->form_validation->set_rules('id', 'id', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
	}
}

/* End of file Urusan.php */
 /* Location: ./app/controllers/Urusan.php */
 /* Please DO NOT modify this information : */
 /* Generated by Ligatcode Codeigniter 4 CRUD Generator 2022-02-19 03:33:06 */