<?php

namespace App\Controllers;

use App\Models\SyUserModel;

class Wf extends BaseController
{
    /**
     * Class constructor.
     */
    protected $SyUserModel; //Default Models Of this Controler
    public function __construct()
    {
        $this->SyUserModel = new SyUserModel(); //Set Default Models Of this Controler
    }

    //ATRIBUTE THIS PAGE
    private function attributePage()
    {
        return  [
            'title' => 'Login | LPPD',
            'app' => 'WinkCode',
        ];
    }

    //INDEX 
    public function index()
    {
        return "<h1>WinkCode System</h1>";
    }

    public function login()
    {
        $data = [];
        return view('login', $data);
    }

    public function login_action()
    {
        $req = service('request');
        // wfDebug($req->getPost());
        $user = $req->getPost()['user'];
        $pass = $req->getPost()['pass'];
        $data = $this->SyUserModel->where('username', $user)->first();
        // die(md5($pass));
        if ($data) {
            $passFromDb = $data['password'];
            // $truePass = \password_verify($pass, $passFromDb);
            if (md5($pass) == $passFromDb) {
                $arrSess = [
                    'logged'   => TRUE,
                    'id_user'  => $data['id'],
                    'username' => $data['username'],
                    'fullname' => $data['fullname'],
                    'telp'     => $data['telp'],
                    'email'    => $data['email'],
                    'foto'     => $data['foto'],
                    'id_group'    => $data['id_group'],
                    'group' => db_connect()->query("select group_name from sy_user_group where id=" . $data['id_group'])->getRow()->group_name
                ];
                session()->set($arrSess);
                return redirect()->to('admin');
            } else {
                session()->setFlashdata('msg', 'Password Anda salah');
                return redirect()->to('wf/login');
            }
        } else {
            session()->setFlashdata('msg', 'Username Anda salah');
            return redirect()->to('wf/login');
        }
    }

    public function logout()
    {
        session()->remove('logged');
        return redirect()->to(base_url() . "/home");
    }
}

/* End of file Ikk.php */
 /* Location: ./app/controllers/Ikk.php */
 /* Please DO NOT modify this information : */
 /* Generated by Ligatcode Codeigniter 4 CRUD Generator 2022-02-19 03:33:21 */